#!/usr/bin/env python3
"""
Batch-analyze all songs from docs/songs_links.csv through the backend API.
The CSV is the single source of truth — this script syncs the DB and
auto-generates frontend/src/data/premadeSongs.ts.

Usage:
    cd backend
    uv run python scripts/preprocess_songs.py

Requires the backend to be running at http://localhost:8000.
"""

import csv
import sqlite3
import sys
import time
import re
from pathlib import Path

import httpx

BASE_URL = "http://localhost:8000"
POLL_INTERVAL = 3  # seconds
TIMEOUT = 180  # 3 minutes per song

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
CSV_PATH = PROJECT_ROOT / "docs" / "songs_links.csv"
DB_PATH = PROJECT_ROOT / "backend" / "data" / "chart_cache.db"
TS_PATH = PROJECT_ROOT / "frontend" / "src" / "data" / "premadeSongs.ts"


def extract_video_id(url: str) -> str | None:
    """Extract YouTube video ID from a URL."""
    patterns = [
        r"(?:v=|\/v\/|youtu\.be\/)([a-zA-Z0-9_-]{11})",
        r"(?:embed\/)([a-zA-Z0-9_-]{11})",
        r"(?:shorts\/)([a-zA-Z0-9_-]{11})",
    ]
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)
    return None


def is_cached(client: httpx.Client, video_id: str) -> bool:
    """Check if a chart already exists in the backend cache."""
    resp = client.get(f"{BASE_URL}/api/chart/{video_id}")
    return resp.status_code == 200


def analyze_song(client: httpx.Client, url: str, title: str, index: int, total: int, bpm_override: float | None = None) -> str:
    """Submit a song for analysis and poll until complete. Returns status string."""
    t0 = time.time()

    # Submit
    payload: dict = {"url": url}
    if bpm_override is not None:
        payload["bpm_override"] = bpm_override
    resp = client.post(f"{BASE_URL}/api/analyze", json=payload)
    if resp.status_code == 429:
        # Rate limited — wait and retry once
        print(f"  Rate limited, waiting 30s...")
        time.sleep(30)
        resp = client.post(f"{BASE_URL}/api/analyze", json=payload)

    if resp.status_code != 200:
        return f"FAIL (HTTP {resp.status_code}: {resp.text})"

    job_id = resp.json()["job_id"]

    # Poll for completion
    while True:
        elapsed = time.time() - t0
        if elapsed > TIMEOUT:
            return f"TIMEOUT ({elapsed:.0f}s)"

        time.sleep(POLL_INTERVAL)
        status_resp = client.get(f"{BASE_URL}/api/status/{job_id}")
        if status_resp.status_code != 200:
            continue

        data = status_resp.json()
        state = data.get("state", data.get("status", ""))

        if state == "complete":
            return f"OK ({elapsed:.0f}s)"
        elif state == "error":
            return f"ERROR: {data.get('error', data.get('message', 'unknown'))}"

        # Still processing — show progress
        progress = data.get("progress", 0)
        message = data.get("message", state)
        print(f"  [{index}/{total}] {title}: {message} ({progress}%)", end="\r")

    return "UNKNOWN"


def mark_premade_in_db(video_ids: set[str]) -> int:
    """Mark all given video_ids as is_premade=1. Returns count updated."""
    if not DB_PATH.exists() or not video_ids:
        return 0
    conn = sqlite3.connect(str(DB_PATH))
    try:
        placeholders = ",".join("?" for _ in video_ids)
        conn.execute(
            f"UPDATE charts SET is_premade = 1 WHERE video_id IN ({placeholders})",
            list(video_ids),
        )
        conn.commit()
        return conn.total_changes
    finally:
        conn.close()


def remove_stale_from_db(csv_video_ids: set[str]) -> int:
    """Remove DB entries whose video_id is not in the CSV. Returns count removed."""
    if not DB_PATH.exists():
        return 0

    conn = sqlite3.connect(str(DB_PATH))
    try:
        rows = conn.execute("SELECT video_id FROM charts").fetchall()
        db_ids = {row[0] for row in rows}
        stale = db_ids - csv_video_ids
        if stale:
            placeholders = ",".join("?" for _ in stale)
            conn.execute(f"DELETE FROM charts WHERE video_id IN ({placeholders})", list(stale))
            conn.commit()
            for vid in sorted(stale):
                print(f"  Removed stale: {vid}")
        return len(stale)
    finally:
        conn.close()


def generate_premade_ts(songs: list[dict]) -> None:
    """Write frontend/src/data/premadeSongs.ts from the CSV song list."""
    lines = [
        "/**",
        " * Video IDs from the curated premade song library (docs/songs_links.csv).",
        " * AUTO-GENERATED by backend/scripts/preprocess_songs.py — do not edit manually.",
        " * Songs with these IDs are displayed as \"premade\" on the HomeScreen.",
        " * Songs NOT in this set are user-added custom songs.",
        " */",
        "export const PREMADE_VIDEO_IDS = new Set([",
    ]
    for song in songs:
        vid = song["video_id"]
        title = song["title"]
        artist = song["artist"]
        lines.append(f"  '{vid}', // {title} — {artist}")
    lines.append("]);")
    lines.append("")  # trailing newline

    TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    TS_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nGenerated {TS_PATH.relative_to(PROJECT_ROOT)} ({len(songs)} IDs)")


def main():
    if not CSV_PATH.exists():
        print(f"CSV not found: {CSV_PATH}")
        sys.exit(1)

    # Parse CSV
    songs = []
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            url = row.get("YouTube Link", "").strip()
            title = row.get("Song Title", "").strip()
            artist = row.get("Artist", "").strip()
            bpm_str = row.get("Approx BPM", "").strip()
            bpm = float(bpm_str) if bpm_str else None
            if url:
                video_id = extract_video_id(url)
                songs.append({"url": url, "title": title, "artist": artist, "video_id": video_id, "bpm": bpm})

    csv_video_ids = {s["video_id"] for s in songs if s["video_id"]}

    print(f"Found {len(songs)} songs in {CSV_PATH.name}\n")

    # Step 1: Remove stale DB entries not in CSV
    print("--- Syncing DB ---")
    removed = remove_stale_from_db(csv_video_ids)
    if removed:
        print(f"Removed {removed} stale entries from DB")
    else:
        print("DB is in sync (no stale entries)")

    # Step 2: Analyze new/missing songs
    print("\n--- Analyzing songs ---")
    succeeded = 0
    failed = 0
    skipped = 0

    with httpx.Client(timeout=30) as client:
        # Verify backend is running
        try:
            client.get(f"{BASE_URL}/api/songs")
        except httpx.ConnectError:
            print(f"Cannot connect to backend at {BASE_URL}")
            print("Make sure the backend is running: cd backend && uv run uvicorn main:app --reload --port 8000")
            sys.exit(1)

        for i, song in enumerate(songs, 1):
            title_display = f"{song['title']} — {song['artist']}"

            # Check cache first
            if song["video_id"] and is_cached(client, song["video_id"]):
                print(f"[{i}/{len(songs)}] SKIP (cached) {title_display}")
                skipped += 1
                continue

            print(f"[{i}/{len(songs)}] Analyzing: {title_display}")
            result = analyze_song(client, song["url"], song["title"], i, len(songs), bpm_override=song.get("bpm"))
            print(f"[{i}/{len(songs)}] {result} {title_display}")

            if result.startswith("OK"):
                succeeded += 1
            else:
                failed += 1

    # Step 3: Mark all CSV songs as premade in the DB
    print("\n--- Marking premade songs in DB ---")
    updated = mark_premade_in_db(csv_video_ids)
    print(f"Marked {updated} songs as premade")

    # Step 4: Generate premadeSongs.ts
    print("\n--- Generating premadeSongs.ts ---")
    generate_premade_ts(songs)

    print(f"\n{'=' * 60}")
    print(f"Done! {succeeded} succeeded, {failed} failed, {skipped} skipped (cached)")
    print(f"Total: {succeeded + skipped}/{len(songs)} songs ready")


if __name__ == "__main__":
    main()
