/**
 * Video IDs from the curated premade song library (docs/songs_links.csv).
 * AUTO-GENERATED by backend/scripts/preprocess_songs.py — do not edit manually.
 * Songs with these IDs are displayed as "premade" on the HomeScreen.
 * Songs NOT in this set are user-added custom songs.
 */
export const PREMADE_VIDEO_IDS = new Set([
  'nfWlot6h_JM', // Shake It Off — Taylor Swift
  '_pYHJWd_yto', // Hey Ya! — Outkast
  'OPf0YbXqDm0', // Uptown Funk — Mark Ronson ft. Bruno Mars
  'p5RobDomh5U', // Can’t Stop the Feeling! — Justin Timberlake
  '9HDEHj2yzew', // Physical — Dua Lipa
  'D8j5Fm94_CE', // Espresso — Sabrina Carpenter
  'LcbAaf_4qtw', // Levels — Avicii
  'y6120QOlsfU', // Sandstorm — Darude
  '0wt4bV3vv7M', // Better Off Alone — Alice Deejay
  '4G6QDNC4jPs', // Everytime We Touch — Cascada
  'gCYcHz2k5x0', // Animals — Martin Garrix
  'PGoCtJzPHkU', // Titanium — David Guetta ft. Sia
  'kTJczUoc26U', // Stay — The Kid LAROI & Justin Bieber
  'CPK2HwYzjkA', // Holding Out for a Hero — Bonnie Tyler
  'djV11Xbc914', // Take On Me — a-ha
  'MdMT_uyGCTs', // Maniac — Michael Sembello
  'aJez0ljzSQw', // Don't Stop Me Now — Queen
  'LaTGrV58wec', // Gonna Make You Sweat — C+C Music Factory
  'SbROFJzWNpc', // Butterfly — Smile.dk
  '_829ZPGv4ts', // Dynamite Rave — Naoki
  'yE-Dpr3Cri8', // MAX 300 — Omega
  'qFgyGhfKDpA', // Beethoven Virus — Diana Boncheva
  '0jgrCKhxE1s', // Through the Fire and Flames — DragonForce
  '6JCLY0Rlx6Q', // Shut Up and Dance — Walk The Moon
  'SeIJmciN8mo', // Starships — Nicki Minaj
  'KRntP-q_R9s', // Bad Guy — Billie Eilish
  'QGJuMBdaqIw', // Firework — Katy Perry
  'AoAm4om0wTs', // Rain On Me — Lady Gaga & Ariana Grande
  'yebNIHKAC4A', // Golden — K-Pop Demon Hunters
  'gdZLi9oWNZg', // Dynamite — BTS
  '9bZkp7q19f0', // Gangnam Style — PSY
  'ioNng23DkIM', // How You Like That — BLACKPINK
  'phuiiNCxRMg', // Supernova — aespa
  'c7rCyll5AeY', // Cheer Up — TWICE
  '2ips2mM7Zqw', // Bang Bang Bang — BIGBANG
  'IHNzOHi8sJs', // DDU-DU DDU-DU — BLACKPINK
  'EaswWiwMVs8', // Thunderous — Stray Kids
  'vLbfv-AAyvQ', // I Am The Best — 2NE1
  'uhG-vLZrb-g', // Sugar We're Goin Down — Fall Out Boy
  'G_sBOsh-vyI', // Knights of Cydonia — Muse
  'A1OqtIqzScI', // Holiday — Green Day
  'CD-E-LDc384', // Enter Sandman — Metallica
  '6fVE8kSM43I', // Duality — Slipknot
  'X4bgXH3sJ2Q', // The Trooper — Iron Maiden
  'GR3Liudev18', // Pink Pony Club — Chappell Roan
  'FGBhQbmPwH8', // One More Time — Daft Punk
  'VBmMU_iwe6U', // Run the World (Girls) — Beyoncé
  '_Yhyp-_hX2s', // Lose Yourself — Eminem
  'tvTRZJ-4EyI', // HUMBLE. — Kendrick Lamar
  '4JipHEz53sU', // Super Bass — Nicki Minaj
  'U9BwWKXjVaI', // Nice For What — Drake
  'ViwtNLUqkMY', // Crazy In Love — Beyoncé ft. Jay-Z
  'GxBSyx85Kp8', // Yeah! — Usher ft. Lil Jon & Ludacris
  'WDZJPJV__bQ', // Formation — Beyoncé
  'CCF1_jI8Prk', // Gasolina — Daddy Yankee
  'kJQP7kiw5Fk', // Despacito — Luis Fonsi ft. Daddy Yankee
  'NUsoVlDFqZg', // Bailando — Enrique Iglesias
]);
